//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Circo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artistas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artistas()
        {
            this.Pagos = new HashSet<Pagos>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Funcao { get; set; }
        public string DataNascimento { get; set; }
        public string CPF { get; set; }
        public string Sexo { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> OmbroAOmbro { get; set; }
        public Nullable<decimal> Ombro { get; set; }
        public Nullable<decimal> Colarinho { get; set; }
        public Nullable<decimal> EntreCavasFrente { get; set; }
        public Nullable<decimal> CentroCosta { get; set; }
        public Nullable<decimal> Busto { get; set; }
        public Nullable<decimal> AlturaBusto { get; set; }
        public Nullable<decimal> SeparacaoBusto { get; set; }
        public Nullable<decimal> Cintura { get; set; }
        public Nullable<decimal> Altura { get; set; }
        public Nullable<decimal> AlturaQuadril { get; set; }
        public Nullable<decimal> Quadril { get; set; }
        public Nullable<decimal> AlturaCinturaDoJoelho { get; set; }
        public Nullable<decimal> AlturaCinturaAoTornozelo { get; set; }
        public Nullable<decimal> ComprimentoBraco { get; set; }
        public Nullable<decimal> LarguraBraco { get; set; }
        public Nullable<decimal> Punho { get; set; }
        public Nullable<decimal> AlturaManga { get; set; }
        public Nullable<decimal> AlturaMangaCurta { get; set; }
        public Nullable<decimal> AlturaDesejadaDaSaia { get; set; }
        public string CaminhoFotoArtista { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos> Pagos { get; set; }

		public override string ToString()
		{
			return Nome + "";
		}
	}
}
