//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Circo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coleções
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coleções()
        {
            this.Peças = new HashSet<Peças>();
        }
    
        public int IDColecao { get; set; }
        public string NMColecao { get; set; }
        public Nullable<int> QtdPeçasUnicas { get; set; }
        public string DTCricao { get; set; }
        public string CostureiraResponsavel { get; set; }
        public string TecidosEAviamentos { get; set; }
        public Nullable<bool> Situacao { get; set; }
        public string Notas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Peças> Peças { get; set; }


		public override string ToString()
		{
			return NMColecao + "";
		}
	}
	
}
