//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Circo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjetoCircoEntities : DbContext
    {
        public ProjetoCircoEntities()
            : base("name=ProjetoCircoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artistas> Artistas { get; set; }
        public virtual DbSet<Coleções> Coleções { get; set; }
        public virtual DbSet<Espetaculos> Espetaculos { get; set; }
        public virtual DbSet<Financeiro> Financeiro { get; set; }
        public virtual DbSet<Local> Local { get; set; }
        public virtual DbSet<Peças> Peças { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Funcionario> Funcionario { get; set; }
    }
}
