//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Circo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Espetaculos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Espetaculos()
        {
            this.Financeiro = new HashSet<Financeiro>();
            this.Local = new HashSet<Local>();
        }
    
        public int IDEspetaculo { get; set; }
        public string NMEspetaculo { get; set; }
        public string DTEspetaculo { get; set; }
        public Nullable<int> IDColecao { get; set; }
        public Nullable<int> IDArtista { get; set; }
    
        public virtual Artistas Artistas { get; set; }
        public virtual Coleções Coleções { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Financeiro> Financeiro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Local> Local { get; set; }
    }
}
