//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Circo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Financeiro
    {
        public int IDFinanceiro { get; set; }
        public string Contratante { get; set; }
        public Nullable<double> TotalReceber { get; set; }
        public Nullable<double> CacheArtista { get; set; }
        public string FormaPagamento { get; set; }
        public string PrevisaoPagamento { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Realizado { get; set; }
        public Nullable<int> IDEspetaculo { get; set; }
    
        public virtual Espetaculos Espetaculos { get; set; }
    }
}
