//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Circo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public int IDFuncionario { get; set; }
        public string CPF { get; set; }
        public string NMFuncionario { get; set; }
        public Nullable<bool> Sexo { get; set; }
        public string RG { get; set; }
        public Nullable<int> DTNascimento { get; set; }
        public string Cargo { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
        public string Foto { get; set; }
        public string Usuario { get; set; }
        public string Senha { get; set; }
    }
}
