//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Circo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalEspetaculo
    {
        public int IDLocal { get; set; }
        public int IDEspetaculo { get; set; }
        public int IDLocalEspetaculo { get; set; }
    
        public virtual Espetaculos Espetaculos { get; set; }
        public virtual Local Local { get; set; }
    }
}
