//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Circo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peças
    {
        public int CDPeças { get; set; }
        public Nullable<int> QtdComponentes { get; set; }
        public Nullable<bool> Reparo { get; set; }
        public Nullable<bool> Situacao { get; set; }
        public string Notas { get; set; }
        public string AnexoCroquis { get; set; }
        public int IDColecao { get; set; }
    
        public virtual Coleções Coleções { get; set; }
    }
}
