//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Circo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peças
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Peças()
        {
            this.Figurino = new HashSet<Figurino>();
        }
    
        public int CDPeças { get; set; }
        public Nullable<int> QtdComponentes { get; set; }
        public Nullable<bool> Reparo { get; set; }
        public Nullable<bool> Situacao { get; set; }
        public string Notas { get; set; }
        public string AnexoCroquis { get; set; }
        public int IDColecao { get; set; }
    
        public virtual Coleções Coleções { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Figurino> Figurino { get; set; }
    }
}
